read_register:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: growatt_datalogger
    target:
      default: inverter
      selector:
        select:
          options:
            - inverter
            - datalogger
    register:
      required: true
      example: 3
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    end_register:
      example: 10
      selector:
        number:
          min: 0
          max: 65535
          mode: box

write_register:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: growatt_datalogger
    target:
      default: inverter
      selector:
        select:
          options:
            - inverter
            - datalogger
    register:
      required: true
      example: 3
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    value:
      required: true
      example: 100
      selector:
        text:
    confirm:
      default: false
      selector:
        boolean:

sync_time:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: growatt_datalogger

adopt_history:
  fields:
    target_entity:
      required: true
      example: sensor.growatt_inverter_sml0examp2_output_energy_total
      selector:
        entity:
          integration: growatt_datalogger
    source_entity_id:
      required: true
      example: sensor.growatt_lifetime_energy_output
      selector:
        text:
    discard_target_statistics:
      default: false
      selector:
        boolean:

write_registers:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: growatt_datalogger
    start_register:
      required: true
      example: 1100
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    values:
      required: true
      example: "[1560, 1740, 1]"
      selector:
        object:
    confirm:
      default: false
      selector:
        boolean:
